# Generated by Django 6.0.5 on 2026-05-09 14:13
# Modified to remove GIS dependencies for Windows compatibility

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('boundary', models.TextField(blank=True)),  # Temporarily store as JSON text instead of GIS field
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Constituencies',
            },
        ),
        migrations.CreateModel(
            name='ElectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('winner_name', models.CharField(max_length=200)),
                ('winner_party', models.CharField(max_length=200)),
                ('winner_votes', models.IntegerField()),
                ('runner_up_name', models.CharField(max_length=200)),
                ('runner_up_votes', models.IntegerField()),
                ('total_votes', models.IntegerField()),
                ('turnout_percent', models.FloatField()),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='db.constituency')),
            ],
        ),
        migrations.CreateModel(
            name='MLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('party', models.CharField(max_length=200)),
                ('education', models.CharField(blank=True, max_length=500)),
                ('term_start', models.IntegerField()),
                ('term_end', models.IntegerField(blank=True, null=True)),
                ('achievements_raw', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mla', to='db.constituency')),
            ],
        ),
        migrations.CreateModel(
            name='MP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('party', models.CharField(max_length=200)),
                ('lok_sabha_seat', models.CharField(max_length=200)),
                ('term_start', models.IntegerField()),
                ('term_end', models.IntegerField(blank=True, null=True)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mp', to='db.constituency')),
            ],
        ),
    ]
