# Generated by Django 6.0.5 on 2026-05-16 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_constituency_boundary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mp',
            name='constituency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mp', to='db.constituency'),
        ),
    ]
