"""
Django settings for geocivic project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import environ
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Read environment variables from .env file
env = environ.Env(
    DEBUG=(bool, True),
    GDAL_LIBRARY_PATH=(str, ''),
)
environ.Env.read_env(BASE_DIR / '.env')

# ---------------------------------------------------------------------------
# Windows: add OSGeo4W bin to the DLL search path so gdal312.dll can load
# its own dependencies (proj, geos, etc.) from the OSGeo4W installation.
# os.add_dll_directory() is available on Python 3.8+ / Windows only.
# ---------------------------------------------------------------------------
_gdal_dll_dir = None
if os.name == 'nt':
    _osgeo4w_bin = r'C:\OSGeo4W\bin'
    if os.path.isdir(_osgeo4w_bin) and _osgeo4w_bin not in os.environ.get('PATH', ''):
        os.environ['PATH'] = _osgeo4w_bin + os.pathsep + os.environ.get('PATH', '')
        _gdal_dll_dir = os.add_dll_directory(_osgeo4w_bin)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = ['testserver', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
<<<<<<< HEAD
    'django.contrib.gis',  # GeoDjango / PostGIS support
    'db',     
    'rest_framework',
    'rest_framework_gis',             # GeoCivic spatial data models
=======
    # 'django.contrib.gis',  # Completely disabled - GeoDjango / PostGIS support
    'db',                  # Re-enabled for testing (models work without GIS)
    'api',                  # Re-enabled for API functionality
>>>>>>> 93da3f46d34717aee5283fc5c58b966410a8be70
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'geocivic.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'geocivic.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# -------------------------------------------------------------------
# GDAL / PostGIS (GeoDjango)
# On Windows, set GDAL_LIBRARY_PATH in your .env to the full path of
# the GDAL DLL, e.g.  C:/OSGeo4W/bin/gdal309.dll
# On Linux/Mac the library is usually discovered automatically.
# -------------------------------------------------------------------
GDAL_LIBRARY_PATH = env('GDAL_LIBRARY_PATH', default='')
